baseURL = 'https://blog.nooz.dev'
languageCode = 'en-us'
title = 'Michael Zheng'

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"
  [[module.imports]]
    path = "github.com/KKKZOZ/hugo-admonitions"

[taxonomies]
category = 'categories'
tag = 'tags'

[markup.goldmark.renderer]
unsafe = true

[params]
favicon = 'https://raw.githubusercontent.com/NoozAbooz/nooz.dev/d6726961d44053c96598d0c4783ae150d97d8b19/blog/assets/img/favicon.png'

[params.sidebar]
emoji = ''
subtitle = 'Electrical Engineering Student'

[params.sidebar.avatar]
enabled = true
local = true
src = 'img/avatar.jpg'

[[menu.social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/NoozAbooz'

[menu.social.params]
icon = 'brand-github'

[[menu.social]]
identifier = 'Instagram'
name = 'Instagram'
url = 'https://instagram.com/nooz_squared'

[menu.social.params]
icon = 'brand-meta'

# [[menu.social]]
# identifier = 'linkedin'
# name = 'LinkedIn'
# url = 'https://www.linkedin.com/in/michael-zheng58'

# [menu.social.params]
# icon = 'brand-linkedin'

[params.widgets]
    homepage = [
        { type = "search" },
        #{ type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        #{ type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]
